### ISSUE TITLE
Backend: Meeting duration handler

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/acm-site#10]
Currently, in `app.js` and `/routes/admin.js`, meetings are handled in the `GET /`, `GET /schedule`, and `GET /admin` routes. Meeting duration is stored in milliseconds in the DB, and there's also a utility function from `util.js` to format meeting duration how we want it.

However, I'm actually editing the query response (which is kind of sketchy, because it's normally `const` in the first place) to update the duration to the formatted duration. I'm not sure if this is a good thing to be doing.

On top of this, I'm blatantly repeating this code:
```
for(let meeting in meetings.rows) {
    const originalDate = meetings.rows[meeting].date;
    meetings.rows[meeting].date = formatDate(originalDate);    
    meetings.rows[meeting].duration = formatDuration(originalDate, meetings.rows[meeting].duration);
}
```
We need to find a better solution for this - I think I'm just missing an obvious solution here.

**Comment by OxygenCobalt** [comment]
Coming from an appdev perspective, the backend shouldn't be doing this, as it's a data layer that can't respond to user configuration. It should give some standard timestamp that the frontend then displays to the user. IIRC HTML has elements for formatting dates from a unix timestamp, so no JS is needed.
