### ISSUE TITLE
Backend: Discord integration

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/acm-site#36]
See if it's possible to add our meetings to the Events tab in Discord upon creation of a meeting on the site.

**Comment by OxygenCobalt** [comment]
Think I found the documentation for this, leaving it here for when we need it: https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event

Would require some non-trivial heuristics to link RSVP with the event, but partial automation would still be valuable.

**Comment by ezrichards** [comment]
Closing as not planned for now as we'll talk more during the year about doing this.
