### ISSUE TITLE
Frontend/Backend: Handle when user title changes

### ISSUE THREAD

**Issue by OxygenCobalt** [ColoradoSchoolOfMines/acm-site#39]
When the title of a user is changed (by becoming an officer or leaving their role), their session on the site should change. Otherwise, this risks a possible vulnerability.

In addition, we should probably change how we are authenticating admins. I have an inkling that `user.is_admin` could be spoofed in a request, but I don't know enough about the authentication mechanism to confirm that.

**Comment by ezrichards** [comment]
Closing this as not planned as #41 is a continuation and overhaul of this issue.
